# Generated by Django 3.1.2 on 2020-10-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user19', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
